# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
import utils.file_uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coach_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(blank=True, related_name='coaches', to='sports.sport')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('division', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.team_logo_upload_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coached_teams', to='teams.coach')),
                ('head_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_coached_teams', to='teams.coach')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('jersey_number', models.IntegerField()),
                ('year_level', models.CharField(choices=[('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('1st_year_college', '1st Year College'), ('2nd_year_college', '2nd Year College'), ('3rd_year_college', '3rd Year College'), ('4th_year_college', '4th Year College')], max_length=20)),
                ('course', models.CharField(choices=[('stem', 'STEM'), ('gas', 'GAS'), ('humss', 'HUMSS'), ('abm', 'ABM'), ('bs_cs', 'BS Computer Science'), ('bs_ba', 'BS Business Administration')], max_length=50)),
                ('position', models.ManyToManyField(blank=True, to='sports.position')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'jersey_number')},
            },
        ),
    ]
