# Generated by Django 5.1.6 on 2025-11-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='course',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year_level',
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Academic Information',
                'verbose_name_plural': 'Academic Information',
                'unique_together': {('year_level', 'course', 'section')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='academic_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.academicinfo'),
        ),
    ]
