# Generated by Django 5.1.6 on 2025-03-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
