# Generated by Django 5.2.8 on 2025-11-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_player_course_remove_player_year_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicinfo',
            options={'ordering': ['year_level'], 'verbose_name': 'Academic Information', 'verbose_name_plural': 'Academic Information'},
        ),
    ]
