# Generated by Django 5.2.8 on 2025-12-03 14:36

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_playerregistration_playerregistrationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistrationdocument',
            name='file',
            field=models.FileField(storage=documents.storage.RawDocumentStorage(), upload_to='registration_documents/'),
        ),
    ]
