# Generated by Django 5.1.6 on 2025-03-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('teams', '0005_rename_positions_player_position'),
        ('users', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coach_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(blank=True, to='sports.sport')),
                ('teams', models.ManyToManyField(blank=True, to='teams.team')),
            ],
        ),
    ]
