# Generated by Django 5.2.8 on 2025-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_use_google_drive_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerregistrationdocument',
            name='google_drive_id',
        ),
        migrations.AlterField(
            model_name='playerregistrationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='registration_documents/'),
        ),
    ]
