# Generated by Django 5.2.8 on 2025-12-03 17:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_revert_to_cloudinary_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistrationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='registration_documents/'),
        ),
    ]
