# Generated by Django 5.2.8 on 2025-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_use_raw_cloudinary_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
