# Generated by Django 5.2.8 on 2025-12-05 12:42

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_fix_jersey_number_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=teams.models.registration_profile_upload_path),
        ),
    ]
