# Generated by Django 5.2.8 on 2025-12-05 13:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_add_profile_to_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistrationdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='registration_documents/'),
        ),
    ]
