# Generated by Django 5.2.8 on 2025-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_increase_file_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
