# Generated by Django 5.1.6 on 2025-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(blank=True, null=True, to='teams.coach'),
        ),
    ]
