# Generated by Django 5.1.6 on 2025-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_remove_coach_teams_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='sports',
        ),
    ]
