# Generated by Django 5.1.6 on 2025-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_alter_sport_slug'),
        ('teams', '0017_alter_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(blank=True, to='sports.position'),
        ),
    ]
