# Generated by Django 5.1.6 on 2025-03-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_remove_player_position_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
    ]
