# Generated by Django 5.1.6 on 2025-04-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_player_course_player_year_level_team_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='course',
            field=models.CharField(choices=[('stem', 'STEM'), ('gas', 'GAS'), ('humss', 'HUMSS'), ('abm', 'ABM'), ('bs_cs', 'BS Computer Science'), ('bs_ba', 'BS Business Administration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_level',
            field=models.CharField(choices=[('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('1st_year_college', '1st Year College'), ('2nd_year_college', '2nd Year College'), ('3rd_year_college', '3rd Year College'), ('4th_year_college', '4th Year College')], max_length=20),
        ),
    ]
