# Generated by Django 5.1.6 on 2025-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_alter_player_course_alter_player_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('male', 'Female'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
