# Generated by Django 5.1.6 on 2025-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_alter_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
