# Generated by Django 5.1.6 on 2025-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
