# Generated by Django 5.1.6 on 2025-05-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0073_alter_leadercategory_options_and_more'),
        ('teams', '0027_remove_team_coach_team_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='sports.sport'),
        ),
    ]
