# Generated by Django 5.1.6 on 2025-05-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_coach_sports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name', 'created_at']},
        ),
    ]
