# Generated by Django 5.1.6 on 2025-05-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_add_team_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
