# Generated by Django 5.1.6 on 2025-10-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_add_team_soft_delete'),
    ]

    operations = [
    ]
