# Generated by Django 5.1.6 on 2025-10-29 08:40

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_auto_20251025_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=teams.models.team_logo_upload_path),
        ),
    ]
