# Generated by Django 5.1.6 on 2025-03-29 09:30

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        full_name = f"{user.first_name} {user.last_name}"
        user.slug = f"{slugify(full_name)}-{user.id}"  # Directly use ID
        user.save(update_fields=['slug'])  # More efficient than full save

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]