# Generated by Django 5.1.6 on 2025-03-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_slug'),
        ('users', '0005_auto_20250329_1741'),
    ]

    operations = [
    ]
