# Generated by Django 5.1.6 on 2025-03-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_0004_user_slug_0005_auto_20250329_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
