# Generated by Django 5.1.6 on 2025-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=10),
        ),
    ]
