# Generated by Django 5.1.6 on 2025-10-29 08:50

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.user_profile_upload_path),
        ),
    ]
