# Generated by Django 5.1.6 on 2025-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_color_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
