# Generated by Django 5.1.6 on 2025-11-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
    ]
