# Generated by Django 5.1.6 on 2025-11-12 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-startDate']},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['startDate'], name='events_even_startDa_39dd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['endDate'], name='events_even_endDate_177d01_idx'),
        ),
    ]
