# Generated by Django 5.1.6 on 2025-03-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('teams', '0003_remove_player_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.AlterField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sport'),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.position'),
        ),
    ]
