# Generated by Django 5.1.6 on 2025-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_player_teams_player_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='positions',
            new_name='position',
        ),
    ]
