# Generated by Django 5.1.6 on 2025-03-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_position'),
        ('teams', '0006_alter_player_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.position'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
