# Generated by Django 5.1.6 on 2025-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_remove_coach_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(blank=True, to='teams.coach'),
        ),
    ]
