# Generated by Django 5.1.6 on 2025-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_alter_sport_slug'),
        ('teams', '0019_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(related_name='positions', to='sports.position'),
        ),
    ]
