# Generated by Django 5.1.6 on 2025-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
