# Generated by Django 5.1.6 on 2025-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
