# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_stats', models.BooleanField(default=True, help_text='Whether this sport requires individual player statistics tracking')),
                ('scoring_type', models.CharField(choices=[('points', 'Points'), ('sets', 'Sets')], default='points', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.sport_banner_upload_path)),
                ('max_players_per_team', models.PositiveIntegerField(default=12, help_text='Maximum players allowed per team roster')),
                ('max_players_on_field', models.PositiveIntegerField(default=5, help_text='Maximum players allowed on the field/court during play')),
                ('has_period', models.BooleanField(default=False)),
                ('max_period', models.PositiveIntegerField(blank=True, help_text='Maximum periods/quarters/sets possible', null=True)),
                ('has_tie', models.BooleanField(default=False)),
                ('has_overtime', models.BooleanField(default=False)),
                ('win_threshold', models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets)', null=True)),
                ('win_points_threshold', models.PositiveIntegerField(blank=True, help_text='Target points needed to win a match (e.g., 3 sets)', null=True)),
                ('win_margin', models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sport is active and can be used for new games')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expression', models.TextField(blank=True, help_text='Python formula using component codes as variables', null=True)),
                ('is_ratio', models.BooleanField(default=False, help_text='Is this formula a ratio (e.g., made/attempt)?')),
                ('uses_point_value', models.BooleanField(default=False, help_text='If True, uses stat_type.point_value in calculations instead of count')),
                ('decimal_places', models.PositiveSmallIntegerField(default=3, help_text='Number of decimal places to round the result to')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportStatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='SportStatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the stat type (e.g. 'Field Goal', 'Assists')", max_length=30)),
                ('display_name', models.CharField(blank=True, help_text='Shortened display name for UI elements', max_length=15, null=True)),
                ('code', models.CharField(blank=True, help_text="Code used in formulas (e.g. 'FG', 'AST')", max_length=20, null=True)),
                ('point_value', models.IntegerField(default=0, help_text='Points awarded for this stat (0 if not a scoring stat)')),
                ('is_team_summary', models.BooleanField(default=False, help_text='If True, this stat appears in team summary statistics')),
                ('is_player_summary', models.BooleanField(default=False, help_text='If True, this stat appears in player summary statistics')),
                ('is_team_comparison', models.BooleanField(default=False, help_text='If True, this stat is used when comparing teams')),
                ('is_record', models.BooleanField(default=False, help_text='If True, this stat can be recorded during games')),
                ('is_points', models.BooleanField(default=False, help_text='If True, this stat is a scoring stat that contributes points')),
                ('is_boxscore', models.BooleanField(default=False, help_text='If True, this stat appears in the game boxscore')),
                ('is_negative', models.BooleanField(default=False, help_text='If True, this stat represents a negative action (like turnovers)')),
                ('category', models.ForeignKey(blank=True, help_text='Category for organizing stats in the UI', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportstatcategory')),
                ('formula', models.ForeignKey(blank=True, help_text='Formula to calculate this stat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.formula')),
                ('sport', models.ForeignKey(help_text='The sport this stat type belongs to', on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('sport', 'name', 'is_record')},
            },
        ),
        migrations.CreateModel(
            name='FormulaComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sports.formula')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportstattype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sport', 'name'), name='unique_position_name_per_sport'), models.UniqueConstraint(fields=('sport', 'abbreviation'), name='unique_position_abbr_per_sport')],
            },
        ),
        migrations.CreateModel(
            name='LeaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the leader category', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order for displaying the category in UI')),
                ('sport', models.ForeignKey(help_text='The sport this leader category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leader_categories', to='sports.sport')),
                ('primary_stat', models.ForeignKey(blank=True, help_text='The primary stat used for ordering leaders in this category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_for_categories', to='sports.sportstattype')),
                ('stat_types', models.ManyToManyField(help_text='Stats used to determine leaders (max 4)', related_name='leader_categories', to='sports.sportstattype')),
            ],
            options={
                'verbose_name': 'Leader Category',
                'verbose_name_plural': 'Leader Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('sport', 'name')},
            },
        ),
    ]
