# Generated by Django 5.1.6 on 2025-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scoring_style', models.CharField(choices=[('points', 'Points'), ('sets', 'Sets'), ('goals', 'Goals'), ('time', 'Time'), ('race', 'Race')], default='points', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
