# Generated by Django 5.1.6 on 2025-11-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing formulas in the UI', null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.sportstatcategory'),
        ),
    ]
