# Generated by Django 5.1.6 on 2025-03-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
