# Generated by Django 5.2.8 on 2025-11-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_formula_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='deciding_set_points_threshold',
            field=models.PositiveIntegerField(blank=True, help_text="Points needed for the final/deciding set (e.g., 15 for volleyball's 5th set). If not set, uses win_points_threshold", null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='win_margin',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum point margin needed to win a set (e.g., 2 points)', null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='win_points_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Target points needed to win a set (e.g., 25 for volleyball)', null=True),
        ),
    ]
