# Generated by Django 5.1.6 on 2025-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_remove_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='scoring_style',
            field=models.CharField(choices=[('points', 'Points'), ('sets', 'Sets'), ('goals', 'Goals')], default='points', max_length=20),
        ),
    ]
