# Generated by Django 5.2.8 on 2025-12-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_sport_deciding_set_points_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this formula is active and can be used for new stats'),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this stat type is active and can be used for new games'),
        ),
    ]
