# Generated by Django 5.1.6 on 2025-03-16 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_sport_scoring_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='scoring_style',
            field=models.CharField(choices=[('points', 'Points'), ('sets', 'Sets')], default='points', max_length=20),
        ),
        migrations.CreateModel(
            name='SportStatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_attempt_based', models.BooleanField(default=False)),
                ('max_value', models.IntegerField(blank=True, help_text='Maximum allowed value (null for unlimited)', null=True)),
                ('applies_to', models.CharField(choices=[('player', 'Player'), ('team', 'Team'), ('both', 'Both')], default='player', help_text='Who this stat applies to (Player/Team/Both)', max_length=10)),
                ('is_negative', models.BooleanField(default=False, help_text='Mark if this stat represents a negative metric')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
    ]
