# Generated by Django 5.1.6 on 2025-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_sport_scoring_style_sportstattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
