# Generated by Django 5.1.6 on 2025-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_sportstattype_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
