# Generated by Django 5.1.6 on 2025-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_sportstattype_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
