# Generated by Django 5.1.6 on 2025-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_sportstattype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
