# Generated by Django 5.1.6 on 2025-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_alter_sportstattype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='scoring_style',
        ),
        migrations.AlterUniqueTogether(
            name='sportstattype',
            unique_together={('sport', 'name')},
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='data_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float')], default='int', max_length=10),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='max_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='applies_to',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_attempt_based',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_negative',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='value',
        ),
    ]
