# Generated by Django 5.1.6 on 2025-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_remove_sport_scoring_style_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sportstattype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='point_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='max_value',
        ),
    ]
