# Generated by Django 5.1.6 on 2025-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_sportstattype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, default=0, null=True),
        ),
    ]
