# Generated by Django 5.1.6 on 2025-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_sport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
