# Generated by Django 5.1.6 on 2025-03-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_alter_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='composite_stats',
            field=models.ManyToManyField(blank=True, related_name='component_of_stats', to='sports.sportstattype'),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_counter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='related_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_stats', to='sports.sportstattype'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sportstattype',
            unique_together={('sport', 'name')},
        ),
    ]
