# Generated by Django 5.1.6 on 2025-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_sportstattype_composite_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='max_players_per_team',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='max_teams_per_game',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
