# Generated by Django 5.1.6 on 2025-03-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_remove_sport_max_teams_per_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='max_players_on_field',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='max_players_per_team',
            field=models.PositiveIntegerField(),
        ),
    ]
