# Generated by Django 5.1.6 on 2025-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_alter_sport_max_players_on_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='calculation_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('percentage', 'Percentage')], default='sum', max_length=20),
        ),
    ]
