# Generated by Django 5.1.6 on 2025-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0018_sportstattype_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='calculation_type',
            field=models.CharField(choices=[('none', 'None'), ('sum', 'Sum'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
    ]
