# Generated by Django 5.1.6 on 2025-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0019_alter_sportstattype_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='has_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='has_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='max_period',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
