# Generated by Django 5.1.6 on 2025-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_sport_has_period_sport_has_tie_sport_max_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='scoring_type',
            field=models.CharField(choices=[('points', 'Points'), ('sets', 'Sets')], default='points', max_length=20),
        ),
    ]
