# Generated by Django 5.1.6 on 2025-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_sport_scoring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='win_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets, 25 points)', null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='max_period',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum periods/quarters/sets possible', null=True),
        ),
    ]
