# Generated by Django 5.1.6 on 2025-04-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_sport_win_threshold_alter_sport_max_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='max_players_on_field',
            field=models.PositiveIntegerField(default=5, help_text='Maximum players allowed on the field/court during play'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='max_players_per_team',
            field=models.PositiveIntegerField(default=12, help_text='Maximum players allowed per team roster'),
        ),
    ]
