# Generated by Django 5.1.6 on 2025-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0023_alter_sport_max_players_on_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='sport_banner/'),
        ),
    ]
