# Generated by Django 5.1.6 on 2025-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_sport_banner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('sport', 'name'), name='unique_position_name_per_sport'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('sport', 'abbreviation'), name='unique_position_abbr_per_sport'),
        ),
    ]
