# Generated by Django 5.1.6 on 2025-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0025_position_unique_position_name_per_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='set_point_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='set_point_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
