# Generated by Django 5.1.6 on 2025-04-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0026_sport_set_point_cap_sport_set_point_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='counter_display_name',
            field=models.CharField(blank=True, help_text='Displayed name for counter stats in recording button', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
