# Generated by Django 5.1.6 on 2025-04-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0027_sportstattype_counter_display_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportstattype',
            old_name='counter_display_name',
            new_name='display_name',
        ),
    ]
