# Generated by Django 5.1.6 on 2025-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0028_rename_counter_display_name_sportstattype_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='is_record',
            field=models.BooleanField(default=False, help_text='Check if the stat is use in recording stats'),
        ),
    ]
