# Generated by Django 5.1.6 on 2025-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0029_sportstattype_is_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportstattype',
            old_name='abbreviation',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_record',
            field=models.BooleanField(default=False, help_text='Check if the stat is use in recording stats else for metrics'),
        ),
    ]
