# Generated by Django 5.1.6 on 2025-04-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0030_rename_abbreviation_sportstattype_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='related_stat',
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='display_name',
            field=models.CharField(blank=True, help_text='Displayed name for counter stats in recording button', max_length=15, null=True),
        ),
    ]
