# Generated by Django 5.1.6 on 2025-04-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0031_remove_sportstattype_related_stat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sportstattype',
            unique_together={('sport', 'name', 'is_record')},
        ),
    ]
