# Generated by Django 5.1.6 on 2025-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0033_alter_sportstattype_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='is_metrics',
            field=models.BooleanField(default=False, help_text='Check if the stat is need to display in summary stats or metrics'),
        ),
    ]
