# Generated by Django 5.1.6 on 2025-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0034_sportstattype_is_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='calculation_type',
            field=models.CharField(choices=[('none', 'None'), ('sum', 'Sum'), ('percentage', 'Percentage'), ('difference', 'Difference'), ('product', 'Product')], default='none', max_length=20),
        ),
    ]
