# Generated by Django 5.1.6 on 2025-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0035_alter_sportstattype_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
