# Generated by Django 5.1.6 on 2025-04-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0036_alter_sportstattype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('expression', models.TextField(help_text='Python-like formula using stat codes as variables')),
            ],
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='calculation_type',
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_metrics',
            field=models.BooleanField(default=False, help_text='Check if the stat should be displayed in summary stats or metrics'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_record',
            field=models.BooleanField(default=False, help_text='Check if the stat is used in recording stats else for metrics'),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='formula',
            field=models.ForeignKey(blank=True, help_text='Formula to calculate this stat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.formula'),
        ),
    ]
