# Generated by Django 5.1.6 on 2025-04-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0037_formula_remove_sportstattype_calculation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='sports.sport'),
            preserve_default=False,
        ),
    ]
