# Generated by Django 5.1.6 on 2025-04-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0038_formula_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formula',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
        migrations.CreateModel(
            name='FormulaComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MADE', 'Made'), ('ATTEMPT', 'Attempt'), ('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('COMPONENT', 'Regular Component')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sports.formula')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportstattype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
