# Generated by Django 5.1.6 on 2025-04-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0039_alter_formula_expression_alter_formula_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='composite_stats',
        ),
    ]
