# Generated by Django 5.1.6 on 2025-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0040_remove_sportstattype_composite_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formulacomponent',
            name='role',
        ),
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(help_text='Python formula using component codes as variables'),
        ),
    ]
