# Generated by Django 5.1.6 on 2025-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0041_remove_formula_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulacomponent',
            options={},
        ),
        migrations.RemoveField(
            model_name='formulacomponent',
            name='order',
        ),
    ]
