# Generated by Django 5.1.6 on 2025-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0042_alter_formulacomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportstattype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='display_name',
            field=models.CharField(blank=True, help_text='Displayed name for metrics', max_length=15, null=True),
        ),
    ]
