# Generated by Django 5.1.6 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0043_alter_sportstattype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
