# Generated by Django 5.1.6 on 2025-04-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0044_alter_position_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='has_tie',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='set_point_cap',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='set_point_threshold',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='win_threshold',
        ),
    ]
