# Generated by Django 5.1.6 on 2025-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0045_remove_sport_has_tie_remove_sport_set_point_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='has_tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='set_point_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='set_point_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='win_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets, 25 points)', null=True),
        ),
    ]
