# Generated by Django 5.1.6 on 2025-04-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0046_sport_has_tie_sport_set_point_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='set_point_cap',
        ),
    ]
