# Generated by Django 5.1.6 on 2025-04-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0047_remove_sport_set_point_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='set_point_threshold',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='win_threshold',
        ),
    ]
