# Generated by Django 5.1.6 on 2025-04-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0048_remove_sport_set_point_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='win_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets)', null=True),
        ),
    ]
