# Generated by Django 5.1.6 on 2025-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0049_sport_win_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='has_over_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='win_margin',
            field=models.PositiveIntegerField(blank=True, help_text='Target value needed to win a match (e.g., 3 sets)', null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='win_points_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Target points needed to win a match (e.g., 3 sets)', null=True),
        ),
    ]
