# Generated by Django 5.1.6 on 2025-04-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0050_sport_has_over_time_sport_win_margin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='has_over_time',
            new_name='has_overtime',
        ),
    ]
