# Generated by Django 5.1.6 on 2025-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0051_rename_has_over_time_sport_has_overtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportstattype',
            old_name='is_metrics',
            new_name='is_summary',
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_box_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_player_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_team_stat',
            field=models.BooleanField(default=False),
        ),
    ]
