# Generated by Django 5.1.6 on 2025-05-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0052_rename_is_metrics_sportstattype_is_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_summary',
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_record',
            field=models.BooleanField(default=False),
        ),
    ]
