# Generated by Django 5.1.6 on 2025-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0053_remove_sportstattype_is_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulacomponent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formulacomponent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
