# Generated by Django 5.1.6 on 2025-05-01 11:52

from django.db import migrations

def update_ft_formula_components(apps, schema_editor):
    Formula = apps.get_model('sports', 'Formula')
    SportStatType = apps.get_model('sports', 'SportStatType')
    FormulaComponent = apps.get_model('sports', 'FormulaComponent')
    
    # Get formula with ID 12 (Free Throw formula)
    ft_formula = Formula.objects.filter(id=12).first()
    if ft_formula:
        # Get the components
        ft_made = SportStatType.objects.filter(code='FT_MA').first()
        ft_attempt = SportStatType.objects.filter(code='FT_AT').first()
        
        if ft_made and ft_attempt:
            # Update or create components with correct order
            FormulaComponent.objects.filter(formula=ft_formula, stat_type=ft_made).update(order=0)
            FormulaComponent.objects.filter(formula=ft_formula, stat_type=ft_attempt).update(order=1)

def reverse_migration(apps, schema_editor):
    pass  # No need to reverse this migration

class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0054_alter_formulacomponent_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_ft_formula_components, reverse_migration),
    ]
