# Generated by Django 5.1.6 on 2025-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0055_update_ft_formula_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='is_ratio',
            field=models.BooleanField(default=False, help_text='Is this formula a ratio (e.g., made/attempt)?'),
        ),
    ]
