# Generated by Django 5.1.6 on 2025-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0056_formula_is_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(blank=True, help_text='Python formula using component codes as variables', null=True),
        ),
    ]
