# Generated by Django 5.1.6 on 2025-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0057_alter_formula_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of decimal places to round the result to'),
        ),
    ]
