# Generated by Django 5.1.6 on 2025-05-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0058_formula_decimal_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportstattype',
            old_name='is_player_stat',
            new_name='is_player_summary',
        ),
        migrations.RenameField(
            model_name='sportstattype',
            old_name='is_team_stat',
            new_name='is_team_summary',
        ),
    ]
