# Generated by Django 5.1.6 on 2025-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0059_rename_is_player_stat_sportstattype_is_player_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='is_player_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_team_stat',
            field=models.BooleanField(default=False),
        ),
    ]
