# Generated by Django 5.1.6 on 2025-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0060_sportstattype_is_player_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='is_team_comparison',
            field=models.BooleanField(default=False),
        ),
    ]
