# Generated by Django 5.1.6 on 2025-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0061_sportstattype_is_team_comparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportstattype',
            old_name='is_box_score',
            new_name='is_boxscore',
        ),
    ]
