# Generated by Django 5.1.6 on 2025-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0062_rename_is_box_score_sportstattype_is_boxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='category',
            field=models.CharField(choices=[('scoring', 'Scoring'), ('performance', 'Performance'), ('offensive', 'Offensive'), ('defensive', 'Defensive'), ('other', 'Other')], default='other', help_text='Category for organizing stats in the UI', max_length=20),
        ),
    ]
