# Generated by Django 5.1.6 on 2025-05-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0063_sportstattype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_counter',
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_points',
            field=models.BooleanField(default=False, help_text='If True, this stat is a scoring stat that contributes points'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='code',
            field=models.CharField(blank=True, help_text="Code used in formulas (e.g. 'FG', 'AST')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='display_name',
            field=models.CharField(blank=True, help_text='Shortened display name for UI elements', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_boxscore',
            field=models.BooleanField(default=False, help_text='If True, this stat appears in the game boxscore'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_negative',
            field=models.BooleanField(default=False, help_text='If True, this stat represents a negative action (like turnovers)'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_player_stat',
            field=models.BooleanField(default=False, help_text='If True, this stat applies to players'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_player_summary',
            field=models.BooleanField(default=False, help_text='If True, this stat appears in player summary statistics'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_record',
            field=models.BooleanField(default=False, help_text='If True, this stat can be recorded during games'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_team_comparison',
            field=models.BooleanField(default=False, help_text='If True, this stat is used when comparing teams'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_team_stat',
            field=models.BooleanField(default=False, help_text='If True, this stat applies to teams'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='is_team_summary',
            field=models.BooleanField(default=False, help_text='If True, this stat appears in team summary statistics'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='name',
            field=models.CharField(help_text="Name of the stat type (e.g. 'Field Goal', 'Assists')", max_length=30),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='point_value',
            field=models.IntegerField(default=0, help_text='Points awarded for this stat (0 if not a scoring stat)'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='sport',
            field=models.ForeignKey(help_text='The sport this stat type belongs to', on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
    ]
