# Generated by Django 5.1.6 on 2025-05-09 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0064_remove_sportstattype_is_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the leader category', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order for displaying the category in UI')),
                ('leader_type', models.CharField(choices=[('game', 'Game Leader'), ('season', 'Season Leader'), ('both', 'Both Game & Season')], default='both', help_text='Whether this applies to game leaders, season leaders, or both', max_length=10)),
                ('sport', models.ForeignKey(help_text='The sport this leader category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leader_categories', to='sports.sport')),
                ('stat_types', models.ManyToManyField(help_text='Stats used to determine leaders (max 4)', related_name='leader_categories', to='sports.sportstattype')),
            ],
            options={
                'verbose_name': 'Leader Category',
                'verbose_name_plural': 'Leader Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('sport', 'name')},
            },
        ),
    ]
