# Generated by Django 5.1.6 on 2025-05-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0065_leadercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadercategory',
            name='leader_type',
        ),
    ]
