# Generated by Django 5.1.6 on 2025-05-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0066_remove_leadercategory_leader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadercategory',
            name='is_point_value',
            field=models.BooleanField(default=False, help_text='If True, use the point value of each stat instead of counting occurrences'),
        ),
    ]
