# Generated by Django 5.1.6 on 2025-05-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0067_leadercategory_is_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadercategory',
            name='is_point_value',
        ),
    ]
