# Generated by Django 5.1.6 on 2025-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0068_remove_leadercategory_is_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstattype',
            name='uses_point_value',
            field=models.BooleanField(default=False, help_text='If True, use the point_value instead of counting occurrences for leaderboards and stats'),
        ),
    ]
