# Generated by Django 5.1.6 on 2025-05-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0069_sportstattype_uses_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='uses_point_value',
            field=models.BooleanField(default=False, help_text='If True, uses stat_type.point_value in calculations instead of count'),
        ),
    ]
