# Generated by Django 5.1.6 on 2025-05-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0070_formula_uses_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='uses_point_value',
        ),
    ]
