# Generated by Django 5.1.6 on 2025-05-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0071_remove_sportstattype_uses_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadercategory',
            name='primary_stat',
            field=models.ForeignKey(blank=True, help_text='The primary stat used for ordering leaders in this category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_for_categories', to='sports.sportstattype'),
        ),
    ]
