# Generated by Django 5.1.6 on 2025-05-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0072_leadercategory_primary_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadercategory',
            options={'ordering': ['name'], 'verbose_name': 'Leader Category', 'verbose_name_plural': 'Leader Categories'},
        ),
        migrations.RemoveField(
            model_name='leadercategory',
            name='display_order',
        ),
    ]
