# Generated by Django 5.1.6 on 2025-09-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0073_alter_leadercategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_player_stat',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_team_stat',
        ),
        migrations.CreateModel(
            name='SportStatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.sportstatcategory'),
        ),
    ]
