# Generated by Django 5.1.6 on 2025-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0074_create_sportstatcategory_and_add_category_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadercategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Leader Category', 'verbose_name_plural': 'Leader Categories'},
        ),
        migrations.AddField(
            model_name='leadercategory',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order for displaying the category in UI'),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_player_stat',
            field=models.BooleanField(default=False, help_text='If True, this stat applies to players'),
        ),
        migrations.AddField(
            model_name='sportstattype',
            name='is_team_stat',
            field=models.BooleanField(default=False, help_text='If True, this stat applies to teams'),
        ),
        migrations.AlterField(
            model_name='sportstattype',
            name='category',
            field=models.CharField(choices=[('scoring', 'Scoring'), ('performance', 'Performance'), ('offensive', 'Offensive'), ('defensive', 'Defensive'), ('other', 'Other')], default='other', help_text='Category for organizing stats in the UI', max_length=20, null=True),
        ),
    ]
