# Generated by Django 5.1.6 on 2025-09-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0075_alter_leadercategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_player_stat',
        ),
        migrations.RemoveField(
            model_name='sportstattype',
            name='is_team_stat',
        ),
    ]
