# Generated by Django 5.1.6 on 2025-09-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0076_remove_sportstattype_is_player_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this sport is active and can be used for new games'),
        ),
    ]
