# Generated by Django 5.1.6 on 2025-10-23 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0077_sport_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstattype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing stats in the UI', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportstatcategory'),
        ),
    ]
