# Generated by Django 5.1.6 on 2025-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0078_alter_sportstattype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstatcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
