# Generated by Django 5.1.6 on 2025-10-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0079_sportstatcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='requires_stats',
            field=models.BooleanField(default=True, help_text='Whether this sport requires individual player statistics tracking'),
        ),
    ]
