# Generated by Django 5.1.6 on 2025-10-29 08:50

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0080_sport_requires_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.sport_banner_upload_path),
        ),
    ]
