# Generated by Django 5.1.6 on 2025-04-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0019_alter_substitution_unique_together'),
        ('leagues', '0010_remove_bracketround_bracket_and_more'),
        ('sports', '0020_sport_has_period_sport_has_tie_sport_max_period'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_type', models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], default='single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='BracketRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.bracket')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.bracketround')),
            ],
        ),
    ]
