# Generated by Django 5.1.6 on 2025-04-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='sport',
        ),
    ]
