# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brackets', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='season',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='leagues.season'),
        ),
    ]
