# Generated by Django 5.1.6 on 2025-04-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0002_remove_bracket_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='brackets.bracketround'),
        ),
        migrations.AlterField(
            model_name='bracketround',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='brackets.bracket'),
        ),
    ]
