# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brackets', '0003_initial'),
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_winner', to='teams.team'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brackets.bracket'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_match', to='games.game'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='next_loser_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_loser_matches', to='brackets.bracketmatch'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='brackets.bracketmatch'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='teams.team'),
        ),
        migrations.AddField(
            model_name='bracketround',
            name='bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='brackets.bracket'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='brackets.bracketround'),
        ),
    ]
