# Generated by Django 5.1.6 on 2025-04-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_alter_bracketmatch_round_alter_bracketround_bracket'),
        ('leagues', '0011_remove_season_record_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='leagues.season'),
        ),
    ]
