# Generated by Django 5.1.6 on 2025-11-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0004_initial'),
        ('teams', '0002_remove_player_course_remove_player_year_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_winner', to='teams.team'),
        ),
    ]
