# Generated by Django 5.1.6 on 2025-04-10 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0004_alter_bracket_season'),
        ('leagues', '0012_alter_league_options_remove_league_end_date_and_more'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bracket',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='next_match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previous_matches', to='brackets.bracketmatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bracketround',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='elimination_type',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.season'),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bracketround',
            name='round_number',
            field=models.PositiveIntegerField(),
        ),
    ]
