# Generated by Django 5.1.6 on 2025-04-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0005_bracket_current_round_bracket_is_complete_and_more'),
        ('leagues', '0012_alter_league_options_remove_league_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='leagues.season'),
        ),
    ]
