# Generated by Django 5.1.6 on 2025-04-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0006_alter_bracket_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='brackets.bracketmatch'),
        ),
    ]
