# Generated by Django 5.1.6 on 2025-04-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0007_alter_bracketmatch_next_match'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='teams.team'),
        ),
    ]
