# Generated by Django 5.1.6 on 2025-04-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0008_alter_bracketmatch_winner'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team'),
        ),
    ]
