# Generated by Django 5.1.6 on 2025-04-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0009_alter_bracketmatch_away_team_and_more'),
        ('games', '0020_alter_game_date_alter_game_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_match', to='games.game'),
        ),
    ]
