# Generated by Django 5.1.6 on 2025-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0010_alter_bracketmatch_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='elimination_type',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination'), ('round_robin', 'Round Robin')], max_length=20),
        ),
    ]
