# Generated by Django 5.1.6 on 2025-04-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0011_alter_bracket_elimination_type'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_winner', to='teams.team'),
            preserve_default=False,
        ),
    ]
