# Generated by Django 5.1.6 on 2025-04-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0012_bracket_winner'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_winner', to='teams.team'),
        ),
    ]
