# Generated by Django 5.1.6 on 2025-04-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0013_alter_bracket_winner'),
        ('leagues', '0013_alter_season_unique_together_season_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='leagues.season'),
        ),
    ]
