# Generated by Django 5.1.6 on 2025-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0014_alter_bracket_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
