# Generated by Django 5.1.6 on 2025-05-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0015_bracketmatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracketmatch',
            name='date',
        ),
    ]
