# Generated by Django 5.1.6 on 2025-11-01 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0016_remove_bracketmatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='next_loser_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_loser_matches', to='brackets.bracketmatch'),
        ),
    ]
