# Generated by Django 5.1.6 on 2025-11-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0017_bracketmatch_next_loser_match'),
        ('games', '0035_remove_scoreupdate_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatch',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_match', to='games.game'),
        ),
    ]
