# Generated by Django 5.1.6 on 2025-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0018_alter_bracketmatch_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='is_filler',
            field=models.BooleanField(default=False),
        ),
    ]
