# Generated by Django 5.1.6 on 2025-11-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0019_bracketmatch_is_filler'),
        ('leagues', '0026_alter_league_logo'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='season',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='leagues.season'),
        ),
    ]
