# Generated by Django 5.2.8 on 2025-11-16 10:34

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.facility_photo_upload_path),
        ),
    ]
