# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('division', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.league_logo_upload_path)),
                ('is_recorded', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='upcoming', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='sports.sport')),
            ],
            options={
                'ordering': [models.Case(models.When(status='ongoing', then=0), models.When(status='upcoming', then=1), default=2, output_field=models.IntegerField()), '-start_date'],
            },
        ),
    ]
