# Generated by Django 5.1.6 on 2025-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('name', 'sport')},
        ),
    ]
