# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder_type', models.CharField(choices=[('public', 'Public'), ('coaches', 'Coaches'), ('coach_personal', 'Coach Personal'), ('players', 'Players'), ('player_personal', 'Player Personal'), ('admin_private', 'Admin Private')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, storage=documents.storage.DocumentCloudinaryStorage(), upload_to='documents/')),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('original', 'Original'), ('copy', 'Copy')], default='original', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('original_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='documents.document')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
