# Generated by Django 5.2.8 on 2025-11-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='google_drive_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID for editing', max_length=100, null=True),
        ),
    ]
