# Generated by Django 5.1.6 on 2025-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_extension'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
    ]
