# Generated by Django 5.1.6 on 2025-10-29 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_folder_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_folder_name_per_parent', violation_error_message='A folder with this name already exists here. Please choose a different name.'),
        ),
    ]
