# Generated by Django 5.2.8 on 2025-11-28 04:26

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_google_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Legacy Cloudinary storage (deprecated)', max_length=255, null=True, storage=documents.storage.DocumentCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='google_drive_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID (primary storage)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, help_text='Google Drive version/modified time', max_length=50, null=True),
        ),
    ]
