# Generated by Django 5.2.8 on 2025-12-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_alter_document_google_drive_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
