# Generated by Django 5.1.6 on 2025-10-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_folder_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_name_per_parent',
        ),
    ]
