# Generated by Django 5.2.8 on 2025-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='google_drive_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID (primary storage)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, help_text='Google Drive version/modified time', max_length=50, null=True),
        ),
    ]
