# Generated by Django 5.2.8 on 2025-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_google_drive_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for documents not yet in Google Drive', max_length=500, null=True),
        ),
    ]
