# Generated by Django 5.1.6 on 2025-11-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_public_id_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='public_id',
        ),
    ]
