# Generated by Django 5.1.6 on 2025-11-06 11:39

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, storage=documents.storage.DocumentCloudinaryStorage(), upload_to='documents/'),
        ),
    ]
