# Generated by Django 5.1.6 on 2025-11-07 10:11

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=documents.storage.DocumentCloudinaryStorage(), upload_to='documents/'),
        ),
    ]
