# Generated by Django 5.1.6 on 2025-11-07 10:16

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, storage=documents.storage.DocumentCloudinaryStorage(), upload_to='documents/'),
        ),
    ]
