# Generated by Django 5.1.6 on 2025-11-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='public_id',
        ),
    ]
