# Generated by Django 5.1.6 on 2025-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_document_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
