# Generated by Django 5.1.6 on 2025-05-23 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('trainings', '0001_initial'), ('trainings', '0002_remove_slug_from_training_category'), ('trainings', '0003_remove_trainingcategory_color_and_more'), ('trainings', '0004_remove_trainingmetric_category_and_more'), ('trainings', '0005_remove_trainingmetric_categories_and_more'), ('trainings', '0006_alter_playertraining_attendance_status'), ('trainings', '0007_alter_trainingmetric_unit'), ('trainings', '0008_trainingsession_metrics'), ('trainings', '0009_playertraining_assigned_metrics'), ('trainings', '0010_playermetricrecord_pt_metric_idx_and_more')]

    initial = True

    dependencies = [
        ('teams', '0026_team_abbreviation'),
        ('teams', '0027_remove_team_coach_team_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Training Categories',
            },
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('cm', 'Centimeters'), ('m', 'Meters'), ('km', 'Kilometers'), ('in', 'Inches'), ('ft', 'Feet'), ('kg', 'Kilograms'), ('lbs', 'Pounds'), ('reps', 'Repetitions'), ('sets', 'Sets'), ('bpm', 'Beats per minute'), ('points', 'Points'), ('%', 'Percentage'), ('rating', 'Rating (1-10)'), ('other', 'Other (specify in description)')], help_text='The unit of measurement for this metric', max_length=30)),
                ('is_lower_better', models.BooleanField(default=True, help_text="Is a lower value better? True for metrics like 'time'.")),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainings.trainingcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('team', 'Team Training'), ('individual', 'Individual Training')], default='team', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='sessions', to='trainings.trainingcategory')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to='teams.coach')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team')),
                ('metrics', models.ManyToManyField(blank=True, related_name='sessions', to='trainings.trainingmetric')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='teams.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_records', to='trainings.trainingsession')),
                ('assigned_metrics', models.ManyToManyField(blank=True, related_name='assigned_player_trainings', to='trainings.trainingmetric')),
            ],
            options={
                'unique_together': {('player', 'session')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_metrics', to='teams.coach')),
                ('player_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='trainings.playertraining')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trainings.trainingmetric')),
            ],
            options={
                'ordering': ['-player_training__session__date', 'metric'],
                'indexes': [models.Index(fields=['player_training', 'metric'], name='pt_metric_idx'), models.Index(fields=['value'], name='metric_value_idx'), models.Index(fields=['metric'], name='metric_only_idx'), models.Index(fields=['player_training'], name='player_training_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['player'], name='player_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session'], name='session_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session', 'player'], name='session_player_idx'),
        ),
    ]
