# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricunit',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this metric unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metric_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playermetricrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_metrics', to='teams.coach'),
        ),
        migrations.AddField(
            model_name='playertraining',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='teams.player'),
        ),
        migrations.AddField(
            model_name='playermetricrecord',
            name='player_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='trainings.playertraining'),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this training category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainings.trainingcategory'),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this training metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='metric_unit',
            field=models.ForeignKey(blank=True, help_text='The unit of measurement for this metric', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='trainings.metricunit'),
        ),
        migrations.AddField(
            model_name='playertraining',
            name='assigned_metrics',
            field=models.ManyToManyField(blank=True, related_name='assigned_player_trainings', to='trainings.trainingmetric'),
        ),
        migrations.AddField(
            model_name='playermetricrecord',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trainings.trainingmetric'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='categories',
            field=models.ManyToManyField(related_name='sessions', to='trainings.trainingcategory'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='trainings.trainingmetric'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='playertraining',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_records', to='trainings.trainingsession'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['player_training', 'metric'], name='pt_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['value'], name='metric_value_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['metric'], name='metric_only_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['player_training'], name='player_training_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['player'], name='player_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session'], name='session_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session', 'player'], name='session_player_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playertraining',
            unique_together={('player', 'session')},
        ),
    ]
