# Generated by Django 5.1.6 on 2025-05-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_slug_from_training_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='trainingcategory',
            name='icon',
        ),
    ]
