# Generated by Django 5.1.6 on 2025-11-12 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('trainings', '0003_trainingsession_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['date'], name='trainings_t_date_d529d2_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['date', 'start_time'], name='trainings_t_date_f9779f_idx'),
        ),
    ]
