# Generated by Django 5.1.6 on 2025-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_remove_trainingcategory_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmetric',
            name='category',
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='categories',
            field=models.ManyToManyField(related_name='metrics', to='trainings.trainingcategory'),
        ),
    ]
