# Generated by Django 5.1.6 on 2025-05-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_remove_trainingmetric_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmetric',
            name='categories',
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainings.trainingcategory'),
            preserve_default=False,
        ),
    ]
