# Generated by Django 5.2.8 on 2025-11-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_trainingsession_trainings_t_date_d529d2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playermetricrecord',
            name='metric_only_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermetricrecord',
            name='player_training_idx',
        ),
        migrations.RemoveIndex(
            model_name='playertraining',
            name='player_idx',
        ),
        migrations.RemoveIndex(
            model_name='playertraining',
            name='session_idx',
        ),
    ]
