# Generated by Django 5.1.6 on 2025-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_remove_trainingmetric_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertraining',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
