# Generated by Django 5.2.8 on 2025-11-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_academicinfo_options'),
        ('trainings', '0005_remove_playermetricrecord_metric_only_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['metric'], name='metric_idx'),
        ),
    ]
