# Generated by Django 5.1.6 on 2025-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_alter_playertraining_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmetric',
            name='unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('cm', 'Centimeters'), ('m', 'Meters'), ('km', 'Kilometers'), ('in', 'Inches'), ('ft', 'Feet'), ('kg', 'Kilograms'), ('lbs', 'Pounds'), ('reps', 'Repetitions'), ('sets', 'Sets'), ('bpm', 'Beats per minute'), ('points', 'Points'), ('%', 'Percentage'), ('rating', 'Rating (1-10)'), ('other', 'Other (specify in description)')], help_text='The unit of measurement for this metric', max_length=30),
        ),
    ]
