# Generated by Django 5.2.8 on 2025-12-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_playermetricrecord_metric_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricunit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this unit is active and can be used for new metrics'),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active and can be used for new sessions/metrics'),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this metric is active and can be used for new sessions'),
        ),
    ]
