# Generated by Django 5.1.6 on 2025-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_alter_trainingmetric_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='trainings.trainingmetric'),
        ),
    ]
