# Generated by Django 5.1.6 on 2025-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_trainingsession_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertraining',
            name='assigned_metrics',
            field=models.ManyToManyField(blank=True, related_name='assigned_player_trainings', to='trainings.trainingmetric'),
        ),
    ]
