# Generated by Django 5.1.6 on 2025-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_remove_team_coach_team_coach'),
        ('trainings', '0009_playertraining_assigned_metrics'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['player_training', 'metric'], name='pt_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['value'], name='metric_value_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['metric'], name='metric_only_idx'),
        ),
        migrations.AddIndex(
            model_name='playermetricrecord',
            index=models.Index(fields=['player_training'], name='player_training_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['player'], name='player_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session'], name='session_idx'),
        ),
        migrations.AddIndex(
            model_name='playertraining',
            index=models.Index(fields=['session', 'player'], name='session_player_idx'),
        ),
    ]
