# Generated by Django 5.1.6 on 2025-05-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_squashed_0010_playermetricrecord_pt_metric_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('normalization_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight to normalize improvements. Lower values for metrics that have naturally large percentage changes.', max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight factor for calculating overall improvement. Higher weight = more impact on overall performance.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='trainingmetric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trainings.trainingcategory'),
        ),
        migrations.AlterField(
            model_name='trainingmetric',
            name='unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('cm', 'Centimeters'), ('m', 'Meters'), ('km', 'Kilometers'), ('in', 'Inches'), ('ft', 'Feet'), ('kg', 'Kilograms'), ('lbs', 'Pounds'), ('reps', 'Repetitions'), ('sets', 'Sets'), ('bpm', 'Beats per minute'), ('points', 'Points'), ('%', 'Percentage'), ('rating', 'Rating (1-10)'), ('other', 'Other')], help_text='The unit of measurement for this metric', max_length=30),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='metric_unit',
            field=models.ForeignKey(blank=True, help_text='The unit of measurement for this metric', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='trainings.metricunit'),
        ),
    ]
