# Generated by Django 5.1.6 on 2025-05-23 08:43

from django.db import migrations


def populate_metric_units(apps, schema_editor):
    MetricUnit = apps.get_model('trainings', 'MetricUnit')
    
    # Create units with appropriate normalization weights
    units = {
        'seconds': {'name': 'Seconds', 'weight': 1.0},
        'minutes': {'name': 'Minutes', 'weight': 1.0},
        'cm': {'name': 'Centimeters', 'weight': 1.0},
        'm': {'name': 'Meters', 'weight': 1.0},
        'km': {'name': 'Kilometers', 'weight': 1.0},
        'in': {'name': 'Inches', 'weight': 1.0},
        'ft': {'name': 'Feet', 'weight': 1.0},
        'kg': {'name': 'Kilograms', 'weight': 1.0},
        'lbs': {'name': 'Pounds', 'weight': 1.0},
        'reps': {'name': 'Repetitions', 'weight': 0.2},  # Lower weight for reps which can have large % changes
        'sets': {'name': 'Sets', 'weight': 0.2},         # Lower weight for sets
        'bpm': {'name': 'Beats per minute', 'weight': 1.0},
        'points': {'name': 'Points', 'weight': 0.5},
        '%': {'name': 'Percentage', 'weight': 1.0},
        'rating': {'name': 'Rating (1-10)', 'weight': 1.0},
        'other': {'name': 'Other', 'weight': 1.0},
    }
    
    # Create unit objects
    for code, data in units.items():
        MetricUnit.objects.create(
            code=code,
            name=data['name'],
            normalization_weight=data['weight'],
            description=f"Unit for {data['name']}"
        )

def reverse_func(apps, schema_editor):
    # Delete all MetricUnit objects
    MetricUnit = apps.get_model('trainings', 'MetricUnit')
    MetricUnit.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_metricunit_trainingmetric_weight_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_metric_units, reverse_func),
    ]
