# Generated by Django 5.1.6 on 2025-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_metric_units_complete'),
        ('trainings', '0015_remove_unit_field'),
    ]

    operations = [
    ]
