# Generated by Django 5.1.6 on 2025-05-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_merge_20250524_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricunit',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='metricunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metricunit',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='metricunit',
            name='normalization_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight to normalize improvements. Lower values for metrics that have naturally large percentage changes.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='trainingmetric',
            name='metric_unit',
            field=models.ForeignKey(blank=True, help_text='The unit of measurement for this metric', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='trainings.metricunit'),
        ),
    ]
