# Generated by Django 5.1.6 on 2025-05-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_safe_merge_20250524'),
        ('trainings', '0017_alter_metricunit_options_metricunit_description_and_more'),
    ]

    operations = [
    ]
