# Generated by Django 5.1.6 on 2025-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_merge_20250524_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricunit',
            name='is_default',
            field=models.BooleanField(default=False, help_text='System default units that cannot be deleted by regular users'),
        ),
    ]
