# Generated by Django 5.1.6 on 2025-05-27 11:35

from django.db import migrations


def populate_default_units(apps, schema_editor):
    """Add default metric units that can't be deleted by regular users"""
    MetricUnit = apps.get_model('trainings', 'MetricUnit')
    
    # Default units based on the frontend configuration
    default_units = [
        # Distance units
        {'code': 'cm', 'name': 'Centimeters', 'normalization_weight': 0.5, 'description': 'Distance measurement in centimeters'},
        {'code': 'm', 'name': 'Meters', 'normalization_weight': 0.3, 'description': 'Distance measurement in meters'},
        {'code': 'km', 'name': 'Kilometers', 'normalization_weight': 0.2, 'description': 'Distance measurement in kilometers'},
        {'code': 'in', 'name': 'Inches', 'normalization_weight': 0.5, 'description': 'Distance measurement in inches'},
        {'code': 'ft', 'name': 'Feet', 'normalization_weight': 0.4, 'description': 'Distance measurement in feet'},
        
        # Weight units
        {'code': 'kg', 'name': 'Kilograms', 'normalization_weight': 0.4, 'description': 'Weight measurement in kilograms'},
        {'code': 'lbs', 'name': 'Pounds', 'normalization_weight': 0.4, 'description': 'Weight measurement in pounds'},
        
        # Time units
        {'code': 'sec', 'name': 'Seconds', 'normalization_weight': 0.6, 'description': 'Time measurement in seconds'},
        {'code': 'min', 'name': 'Minutes', 'normalization_weight': 0.7, 'description': 'Time measurement in minutes'},
        {'code': 'hr', 'name': 'Hours', 'normalization_weight': 0.8, 'description': 'Time measurement in hours'},
        
        # Percentage and ratings
        {'code': '%', 'name': 'Percentage', 'normalization_weight': 1.0, 'description': 'Percentage measurement'},
        {'code': 'rating', 'name': 'Rating', 'normalization_weight': 1.0, 'description': 'Rating scale (typically 1-10)'},
        
        # Counts and scores
        {'code': 'reps', 'name': 'Repetitions', 'normalization_weight': 0.3, 'description': 'Number of repetitions'},
        {'code': 'sets', 'name': 'Sets', 'normalization_weight': 0.5, 'description': 'Number of sets'},
        {'code': 'points', 'name': 'Points', 'normalization_weight': 0.4, 'description': 'Score points'},
        
        # Physiological measures
        {'code': 'bpm', 'name': 'Beats per Minute', 'normalization_weight': 0.8, 'description': 'Heart rate measurement'},
    ]
    
    # Create default units
    for unit_data in default_units:
        # Check if unit already exists (in case of re-running migration)
        if not MetricUnit.objects.filter(code=unit_data['code']).exists():
            MetricUnit.objects.create(
                code=unit_data['code'],
                name=unit_data['name'],
                normalization_weight=unit_data['normalization_weight'],
                description=unit_data['description'],
                is_default=True
            )


def reverse_default_units(apps, schema_editor):
    """Remove default units"""
    MetricUnit = apps.get_model('trainings', 'MetricUnit')
    MetricUnit.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_add_is_default_to_metric_unit'),
    ]

    operations = [
        migrations.RunPython(populate_default_units, reverse_default_units),
    ]
