# Generated by Django 5.1.6 on 2025-05-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_populate_default_metric_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricunit',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this metric unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metric_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
