# Generated by Django 5.1.6 on 2025-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0021_add_created_by_to_metricunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
