# Generated by Django 5.1.6 on 2025-06-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_alter_coach_options'),
        ('trainings', '0022_trainingsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='training_type',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team'),
        ),
    ]
