# Generated by Django 5.1.6 on 2025-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_remove_coach_and_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermetricrecord',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The recorded value for this metric', max_digits=10, null=True),
        ),
    ]
