# Generated by Django 5.1.6 on 2025-09-01 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_alter_playermetricrecord_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Training Categories'},
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this training category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='is_default',
            field=models.BooleanField(default=False, help_text='System default categories that cannot be deleted by regular users'),
        ),
    ]
