# Generated by Django 5.1.6 on 2025-09-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0025_alter_trainingcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmetric',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this training metric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='is_default',
            field=models.BooleanField(default=False, help_text='System default metrics that cannot be deleted by regular users'),
        ),
    ]
