# Generated by Django 5.1.6 on 2025-03-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0008_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstat',
            name='attempted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='made',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team'),
        ),
    ]
