# Generated by Django 5.1.6 on 2025-11-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('leagues', '0001_initial'),
        ('sports', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='leagues.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='teams.team'),
        ),
        migrations.AddField(
            model_name='gamecoachpermission',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamecoachpermission',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamecoachpermission',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_permissions', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameset',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameset',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='teams.player'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportstattype'),
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_updates', to='games.game'),
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startinglineup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_lineup', to='games.game'),
        ),
        migrations.AddField(
            model_name='startinglineup',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player'),
        ),
        migrations.AddField(
            model_name='startinglineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='games.game'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='substitute_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_in', to='teams.player'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='substitute_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_out', to='teams.player'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='games_game_date_b7173e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_game_status_da80c5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['home_team', 'away_team'], name='games_game_home_te_c15004_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['started_at'], name='games_game_started_2cd822_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['ended_at'], name='games_game_ended_a_731c30_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecoachpermission',
            index=models.Index(fields=['game', 'coach'], name='games_gamec_game_id_f83831_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecoachpermission',
            index=models.Index(fields=['coach'], name='games_gamec_coach_i_4b3a9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamecoachpermission',
            unique_together={('game', 'coach')},
        ),
        migrations.AlterUniqueTogether(
            name='gameset',
            unique_together={('game', 'period')},
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['game', 'player'], name='games_playe_game_id_8b6c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['stat_type'], name='games_playe_stat_ty_12a153_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreupdate',
            index=models.Index(fields=['game', 'team'], name='games_score_game_id_9a3798_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreupdate',
            index=models.Index(fields=['period'], name='games_score_period_16469c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startinglineup',
            unique_together={('game', 'player')},
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['game', 'period'], name='games_subst_game_id_488701_idx'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['substitute_in', 'substitute_out'], name='games_subst_substit_49b6fe_idx'),
        ),
    ]
