# Generated by Django 5.1.6 on 2025-11-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_status_da80c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_ended_a_731c30_idx',
        ),
    ]
