# Generated by Django 5.2.8 on 2025-11-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_games_game_status_da80c5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamecoachpermission',
            name='games_gamec_coach_i_4b3a9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerstat',
            name='games_playe_stat_ty_12a153_idx',
        ),
    ]
