# Generated by Django 5.1.6 on 2025-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_teamstat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
