# Generated by Django 5.1.6 on 2025-03-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_teamstat_game_remove_teamstat_stat_type_and_more'),
        ('sports', '0011_alter_sportstattype_unique_together_and_more'),
        ('teams', '0008_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportstattype')),
            ],
        ),
    ]
