# Generated by Django 5.2.8 on 2026-01-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20251118_1304'),
        ('teams', '0012_alter_playerregistration_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forfeited_by',
            field=models.ForeignKey(blank=True, help_text="The team that forfeited the game (only set when status is 'forfeited')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_forfeited', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('default_home_win', 'Default Win (Home)'), ('default_away_win', 'Default Win (Away)'), ('double_default', 'Double Default'), ('forfeited', 'Forfeited')], default='scheduled', max_length=20),
        ),
    ]
