# Generated by Django 5.1.6 on 2025-03-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_playerstat'),
        ('sports', '0013_alter_sport_slug'),
        ('teams', '0018_remove_player_position_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='games_game_date_b7173e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_game_status_da80c5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['home_team', 'away_team'], name='games_game_home_te_c15004_idx'),
        ),
    ]
