# Generated by Django 5.2.8 on 2026-03-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_practice_game_rosters'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='practicegameplayer',
            new_name='games_pract_game_id_588cd5_idx',
            old_name='games_pract_game_id_b90f08_idx',
        ),
        migrations.RenameIndex(
            model_name='practicegameplayer',
            new_name='games_pract_practic_bfd600_idx',
            old_name='games_pract_practic_22ec5c_idx',
        ),
        migrations.RenameIndex(
            model_name='practicegameplayer',
            new_name='games_pract_player__f20085_idx',
            old_name='games_pract_player__1de203_idx',
        ),
        migrations.RenameIndex(
            model_name='practicegameteam',
            new_name='games_pract_game_id_988068_idx',
            old_name='games_pract_game_id_7f77cd_idx',
        ),
    ]
