# Generated by Django 5.1.6 on 2025-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_status'),
        ('sports', '0013_alter_sport_slug'),
        ('teams', '0018_remove_player_position_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['started_at'], name='games_game_started_2cd822_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['ended_at'], name='games_game_ended_a_731c30_idx'),
        ),
    ]
