# Generated by Django 5.1.6 on 2025-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_duration_game_ended_at_game_notes_and_more'),
        ('sports', '0014_sportstattype_composite_stats_and_more'),
        ('teams', '0019_alter_player_options_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['game', 'player'], name='games_playe_game_id_8b6c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['stat_type', 'success'], name='games_playe_stat_ty_7df4ca_idx'),
        ),
    ]
