# Generated by Django 5.1.6 on 2025-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_playerstat_options_and_more'),
        ('sports', '0014_sportstattype_composite_stats_and_more'),
        ('teams', '0019_alter_player_options_alter_player_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerstat',
            name='games_playe_stat_ty_7df4ca_idx',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='success',
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['stat_type'], name='games_playe_stat_ty_12a153_idx'),
        ),
    ]
