# Generated by Django 5.1.6 on 2025-03-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_playerstat_games_playe_stat_ty_7df4ca_idx_and_more'),
        ('sports', '0017_alter_sport_max_players_on_field_and_more'),
        ('teams', '0019_alter_player_options_alter_player_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
        migrations.CreateModel(
            name='StartingLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_lineup', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('substitute_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_in', to='teams.player')),
                ('substitute_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_out', to='teams.player')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('game', 'substitute_out', 'period')},
            },
        ),
    ]
