# Generated by Django 5.1.6 on 2025-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_game_notes_startinglineup_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='startinglineup',
            name='is_starting',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
