# Generated by Django 5.1.6 on 2025-04-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_game_status_alter_startinglineup_is_starting'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.season'),
            preserve_default=False,
        ),
    ]
