# Generated by Django 5.1.6 on 2025-04-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_game_league_game_season'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='leagues.league'),
        ),
    ]
