# Generated by Django 5.1.6 on 2025-04-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_league_alter_game_season'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='games.game'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['game', 'period'], name='games_subst_game_id_488701_idx'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['substitute_in', 'substitute_out'], name='games_subst_substit_49b6fe_idx'),
        ),
    ]
