# Generated by Django 5.1.6 on 2025-04-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_playerstat_player_alter_substitution_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startinglineup',
            name='is_starting',
            field=models.BooleanField(default=True),
        ),
    ]
