# Generated by Django 5.1.6 on 2025-04-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_startinglineup_is_starting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substitution',
            unique_together=set(),
        ),
    ]
