# Generated by Django 5.1.6 on 2025-04-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_game_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
    ]
