# Generated by Django 5.1.6 on 2025-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='recorded',
            field=models.BooleanField(default=True),
        ),
    ]
