# Generated by Django 5.1.6 on 2025-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_game_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
    ]
