# Generated by Django 5.1.6 on 2025-04-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_alter_game_recorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='recorded',
            new_name='is_recorded',
        ),
    ]
