# Generated by Django 5.1.6 on 2025-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_rename_recorded_game_is_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('league', 'League'), ('tournament', 'Tournament'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
