# Generated by Django 5.1.6 on 2025-04-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_gameset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startinglineup',
            name='is_starting',
        ),
        migrations.RemoveField(
            model_name='startinglineup',
            name='position',
        ),
    ]
