# Generated by Django 5.1.6 on 2025-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_remove_startinglineup_is_starting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startinglineup',
            name='is_starting',
            field=models.BooleanField(default=True),
        ),
    ]
