# Generated by Django 5.1.6 on 2025-05-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_startinglineup_is_starting'),
        ('teams', '0026_team_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='teams.team'),
        ),
    ]
