# Generated by Django 5.1.6 on 2025-05-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_game_winner_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('league', 'League'), ('tournament', 'Tournament'), ('practice', 'Practice')], default='practice', max_length=20),
        ),
    ]
