# Generated by Django 5.1.6 on 2025-06-19 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_alter_game_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCoachPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_permissions', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_permissions', to='games.game')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'coach'], name='games_gamec_game_id_f83831_idx'), models.Index(fields=['coach'], name='games_gamec_coach_i_4b3a9b_idx')],
                'unique_together': {('game', 'coach')},
            },
        ),
    ]
