# Generated by Django 5.1.6 on 2025-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_gamecoachpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True, help_text='Game time', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, help_text='Game date', null=True),
        ),
    ]
