# Generated by Django 5.1.6 on 2025-10-24 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_game_time_alter_game_date'),
        ('teams', '0032_add_team_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Points added (can be negative for corrections)')),
                ('period', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, help_text='Optional reason for score update', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_updates', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['game', 'team'], name='games_score_game_id_9a3798_idx'), models.Index(fields=['period'], name='games_score_period_16469c_idx')],
            },
        ),
    ]
