# Generated by Django 5.1.6 on 2025-10-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_scoreupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreupdate',
            name='reason',
        ),
    ]
