# Generated by Django 5.1.6 on 2025-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='leagues', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name', 'sport')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'name')},
        ),
    ]
