# Generated by Django 5.1.6 on 2025-04-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_season_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='is_active',
        ),
    ]
