# Generated by Django 5.1.6 on 2025-04-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_remove_season_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
    ]
