# Generated by Django 5.1.6 on 2025-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_remove_season_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='elimination_type',
            field=models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination')], default='single_elimination', max_length=20),
        ),
    ]
