# Generated by Django 5.1.6 on 2025-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_season_record_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='upcoming', max_length=20),
        ),
    ]
