# Generated by Django 5.1.6 on 2025-04-09 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_substitution_unique_together'),
        ('leagues', '0007_season_status'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('match_number', models.PositiveIntegerField()),
                ('winner_to', models.PositiveIntegerField(blank=True, null=True)),
                ('loser_to', models.PositiveIntegerField(blank=True, null=True)),
                ('is_losers_bracket', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches', to='leagues.league')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
            },
        ),
    ]
