# Generated by Django 5.1.6 on 2025-04-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_bracketmatch'),
        ('sports', '0020_sport_has_period_sport_has_tie_sport_max_period'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracketmatch',
            options={},
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='is_losers_bracket',
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='league',
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='loser_to',
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='bracketmatch',
            name='winner_to',
        ),
        migrations.RemoveField(
            model_name='league',
            name='elimination_type',
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='bracketmatch',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team'),
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_type', models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], default='single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.bracket'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BracketRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.bracket')),
            ],
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.bracketround'),
            preserve_default=False,
        ),
    ]
