# Generated by Django 5.1.6 on 2025-04-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_remove_bracketround_bracket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='record_stats',
        ),
    ]
