# Generated by Django 5.1.6 on 2025-04-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_remove_season_record_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='league',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='league',
            name='start_date',
        ),
    ]
