# Generated by Django 5.1.6 on 2025-04-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_alter_league_options_remove_league_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'year', 'name')},
        ),
    ]
