# Generated by Django 5.1.6 on 2025-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_alter_season_unique_together_season_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
