# Generated by Django 5.1.6 on 2025-04-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_alter_season_end_date_alter_season_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
    ]
