# Generated by Django 5.1.6 on 2025-04-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_league_logo'),
        ('teams', '0020_player_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='leagues', to='teams.team'),
        ),
    ]
