# Generated by Django 5.1.6 on 2025-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_remove_league_teams_season_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='recorded',
            field=models.BooleanField(default=True),
        ),
    ]
