# Generated by Django 5.1.6 on 2025-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_rename_recorded_season_is_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(),
        ),
    ]
