# Generated by Django 5.1.6 on 2025-05-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_alter_season_start_date'),
        ('teams', '0026_team_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_seasons', to='teams.team'),
        ),
    ]
