# Generated by Django 5.1.6 on 2025-05-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_season_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='winner',
        ),
    ]
