# Generated by Django 5.1.6 on 2025-06-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_remove_season_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'name')},
        ),
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
    ]
