# Generated by Django 5.1.6 on 2025-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_alter_season_options_alter_season_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': [models.Case(models.When(status='ongoing', then=0), models.When(status='upcoming', then=1), default=2, output_field=models.IntegerField()), '-start_date']},
        ),
    ]
