# Generated by Django 5.1.6 on 2025-09-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_alter_season_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='division',
            field=models.CharField(choices=[('men', 'Men'), ('Women', 'Women')], default='men', max_length=10),
        ),
    ]
