# Generated by Django 5.1.6 on 2025-09-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_league_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='division',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
