# Generated by Django 5.1.6 on 2025-10-29 08:50

import utils.file_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0025_alter_league_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_uploads.league_logo_upload_path),
        ),
    ]
