# Generated by Django 5.2.8 on 2025-12-02 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_fcmdevice_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event', 'Event'), ('league_game', 'League Game'), ('tournament_game', 'Tournament Game'), ('practice_game', 'Practice Game'), ('bulk_games', 'Bulk Games'), ('training', 'Training Session'), ('facility', 'Facility Reservation'), ('facility_status', 'Facility Reservation Status'), ('chat', 'Chat Message')], max_length=20)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_change', 'Status Change')], default='created', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('click_action', models.URLField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_ecc0c6_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_be328b_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_e9d5ed_idx')],
            },
        ),
    ]
