# Generated by Django 5.2.8 on 2025-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
